apiVersion: cluster.open-cluster-management.io/v1beta2 #bind managed clusters to the target namespace where Argo CD is deployed
kind: ManagedClusterSetBinding
metadata:
  name: demo
  namespace: openshift-gitops
spec:
  clusterSet: demo