apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: build-app-pipeline-trigger-template
  namespace: user1-dev
  annotations:
    triggers.tekton.dev/old-escape-quotes: 'true'
spec:
  params:
    - name: repo
      description: The Git repo name
    - name: branch
      description: The Git repo branch name
    - name: hook-type
      description: The Webhook type - branch or tag
    - name: username
      description: The user that created the branch
    - name: repo_name
      description: "Name of the repo/app: app-a, app-b or app-c"
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-app-
      spec:
        params:
          - name: app
            value: $(tt.params.repo_name)
          - name: GIT_REPO
            value: $(tt.params.repo)
          - name: GIT_REVISION
            value: $(tt.params.branch)
          - name: PATH_CONTEXT
            value: .
          - name: VERSION
            value: openjdk-17-ubi8
        pipelineRef:
          name: build-app
        serviceAccountName: pipeline
        timeout: 1h0m0s
        workspaces:
          - name: git-basic-auth
            secret:
              secretName: git-basic-auth
          - name: source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding #map inputs from event listener into params that will be used by TriggerTemplate 
metadata:
  name: build-app-pipeline-trigger-binding
  namespace: user1-dev
spec:
  # https://docs.gitea.com/next/usage/webhooks#event-information
  params:
    - name: repo
      value: "$(body.repository.clone_url)"
    - name: repo_name
      value: "$(body.repository.name)"
    - name: branch
      value: "$(body.ref)"
    - name: hook-type
      value: "$(header.X-Gitea-Event)"
    - name: username
      value: "$(body.sender.username)"
---
apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: build-app-pipeline-trigger
  namespace: user1-dev
spec:
  interceptors: []
  bindings:
  - ref: build-app-pipeline-trigger-binding
  template:
    ref: build-app-pipeline-trigger-template
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: build-app-pipeline-trigger-listener
spec:
  serviceAccountName: pipeline
  triggers:
  - triggerRef: build-app-pipeline-trigger

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: build-app-trigger
  namespace: user1-dev
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-build-app-pipeline-trigger-listener
    weight: 100
  wildcardPolicy: None
  tls:
    termination: edge
  insecureEdgeTerminationPolicy: Redirect