apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- common/
- app-a/
- app-b/
- app-c/
- servicemesh/
#TODO add service mesh resource folder

# Testing:
#   kustomize edit set image app-a:latest=image-registry.openshift-image-registry.svc:5000/user1-apps/app-a:main
#
images:
- digest: sha256:6cc83f7c50bcfb51d8677ab543ba2203688be5e5bb36532600d1d513290382da
  name: app-a:latest
  newName: image-registry.openshift-image-registry.svc:5000/user1-apps/app-a
- digest: sha256:f8e42308c88134fe15fecb8468513d551aae487b6b041cf146bd74911297f16b
  name: app-b:latest
  newName: image-registry.openshift-image-registry.svc:5000/user1-apps/app-b
- digest: sha256:fa6b8a08491807172e0a4237024979a2ad7700def3f3420e0ce5c5c0a98241ad
  name: app-c:latest
  newName: image-registry.openshift-image-registry.svc:5000/user1-apps/app-c
